In [5]:
import numpy as np
import csv

def min_max_normalize(x):
    """
    Performs min-max normalization on a dataset or vector.

    Args:
        -x: A dataset to be normalized.

    Returns:
        A normalized version of x, where each value is scaled between 0 and 1.
    """    
    #Get the min value of the dataset
    min_val = np.min(x, axis=0)
    #Get the max value of the dataset
    max_val = np.max(x, axis=0)
    #min_max normalization
    normalized_x = (x - min_val) / (max_val - min_val)
    return normalized_x

gps_data=[]
with open("my_project/controllers/my_controller/gps_hand.csv", "r", newline='') as gps_csvfile:
    gps_reader = csv.reader(gps_csvfile)
   
    for row in gps_reader:
        gps_data.append([float(value) for value in row[1:]])  # Pasar la columna del indice
        
gps_data=min_max_normalize(gps_data)

for i in gps_data:
    print(i)

[0.75175857 0.56932303 0.49649494]
[0.73953784 0.49116274 0.63336718]
[0.75284636 0.36048188 0.47875195]
[0.7609543  0.44229397 0.58471239]
[0.74707016 0.42975855 0.54699318]
[0.73549818 0.45864217 0.58990897]
[0.63539231 0.43392986 0.66734945]
[0.73175272 0.43641457 0.50477591]
[0.71455532 0.45113006 0.46822159]
[0.77434217 0.6372289  0.58537522]
[0.78408663 0.57467305 0.5417126 ]
[0.76868379 0.60730882 0.46253998]
[0.78357917 0.53159452 0.60263568]
[0.78318674 0.4669591  0.48573967]
[0.74996383 0.45274286 0.53907322]
[0.8037188  0.58990211 0.44408323]
[0.76673579 0.65144935 0.53305088]
[0.74873466 0.6458616  0.4636029 ]
[0.77416732 0.46378138 0.62992409]
[0.72981648 0.55613501 0.71368373]
[0.6684493  0.61610853 0.74294216]
[0.57652136 0.49941331 0.80976598]
[0.66595272 0.5536882  0.7522681 ]
[0.67633074 0.54975951 0.70219959]
[0.66162664 0.57447323 0.7117297 ]
[0.65375265 0.59620173 0.67000479]
[0.62863602 0.60216055 0.68351125]
[0.65563653 0.61720556 0.61272454]
[0.73758873 0.607483

[0.64675696 0.39350441 0.64087542]
[0.65850764 0.42226047 0.61122015]
[0.67319972 0.4635235  0.50075108]
[0.60941554 0.46383886 0.37821663]
[0.46814181 0.3999784  0.28912109]
[0.37963447 0.45034384 0.21150313]
[0.59032857 0.50948476 0.31670415]
[0.60647205 0.52935138 0.36255284]
[0.58237449 0.38507506 0.389793  ]
[0.61071452 0.41042781 0.51323757]
[0.58653739 0.54423627 0.71619761]
[0.64210743 0.49210207 0.62378755]
[0.53139949 0.54915723 0.76379509]
[0.44452742 0.41429103 0.82172148]
[0.63183283 0.38544758 0.66253014]
[0.68394692 0.46808154 0.63015001]
[0.62261794 0.54559635 0.69748071]
[0.54003947 0.50574321 0.7139635 ]
[0.65789271 0.46599399 0.51308526]
[0.65225427 0.51293491 0.41502411]
[0.58565741 0.42071007 0.44052046]
[0.58265737 0.48589643 0.47117442]
[0.55327476 0.52883109 0.50593342]
[0.54697795 0.38305996 0.69738271]
[0.59401889 0.27778722 0.59104064]
[0.52249041 0.22256272 0.46011186]
[0.48653482 0.25368896 0.39655885]
[0.44787975 0.27613519 0.29913914]
[0.67217063 0.367747

[0.60559079 0.35800276 0.62754345]
[0.64782823 0.48048003 0.55780831]
[0.70424635 0.6282203  0.56776299]
[0.65777229 0.58315926 0.56144389]
[0.60988963 0.57626241 0.67059178]
[0.51251047 0.626298   0.75759074]
[0.37526618 0.52960004 0.86946671]
[0.45679686 0.49783088 0.80541035]
[0.66024654 0.50610868 0.64915677]
[0.69955521 0.50602973 0.62317521]
[0.71539556 0.54985565 0.55124016]
[0.67514506 0.47959846 0.55359983]
[0.63546926 0.4420878  0.57887529]
[0.67274502 0.44497889 0.3976042 ]
[0.71358126 0.46886634 0.50338394]
[0.67472899 0.45680134 0.55278315]
[0.67649473 0.52066735 0.53611156]
[0.68788109 0.60912249 0.72745617]
[0.80692172 0.48102977 0.57128687]
[0.76038622 0.54913451 0.69835843]
[0.81311635 0.72274583 0.66324199]
[0.74293996 0.62214051 0.75568929]
[0.82801969 0.6871632  0.6261852 ]
[0.83278334 0.6393976  0.5242583 ]
[0.78315048 0.61800066 0.58027212]
[0.71225521 0.55896177 0.60167908]
[0.72835424 0.5792755  0.53740204]
[0.75590375 0.5674576  0.42723641]
[0.63973576 0.499807

[0.62540274 0.45591093 0.45343404]
[0.65103737 0.46998018 0.52905315]
[0.58093155 0.40087708 0.39756703]
[0.53960225 0.40073728 0.33638767]
[0.42123678 0.44735874 0.21209498]
[0.45404729 0.35334217 0.28008702]
[0.50051642 0.20209912 0.42672662]
[0.34797628 0.13781338 0.28160738]
[0.58009655 0.28455976 0.31788541]
[0.51714469 0.1551493  0.46092538]
[0.47959254 0.17379271 0.42827043]
[0.60886935 0.33858895 0.31908556]
[0.57308958 0.33437569 0.35274341]
[0.72429844 0.45068726 0.48963579]
[0.6559915  0.41273198 0.53290273]
[0.59251662 0.41636075 0.60814201]
[0.63583853 0.42183896 0.49741641]
[0.56322715 0.38273325 0.53083263]
[0.58071237 0.42896753 0.43716345]
[0.54365713 0.47796382 0.2681117 ]
[0.52336948 0.27151653 0.36715614]
[0.60073735 0.40643976 0.43255534]
[0.59098136 0.40044549 0.54326165]
[0.61011483 0.4710276  0.41202221]
[0.52182271 0.36102224 0.36806232]
[0.44382481 0.35618321 0.26477059]
[0.31868316 0.33921613 0.18849596]
[0.48100937 0.34676884 0.29984248]
[0.43592535 0.407335